name: Integration Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 8080:8080
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Set up pnpm
        run: npm install -g pnpm@8
      - name: Install dependencies
        run: pnpm install
      - name: Run integration tests
        run: pnpm test # Make sure this command runs your integration tests
        env:
          AUTHORIZER_IMAGE: quay.io/authorizer/authorizer:2.4.0-rc.7
